---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4
    cpuexecutioncap: 80

provisioner:
  name: chef_solo
  client_rb:
    environment: testing

platforms:
  - name: ubuntu-14.04

suites:
  - name: testing
    run_list:
      - recipe[patchdashboard::default]
    attributes:
